version: "3.5"

services:

  https-portal:
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
    environment:
      DOMAINS: >
        jenkins.test -> http://jenkins:8080,
      CLIENT_MAX_BODY_SIZE: 1024M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - jenkins
    depends_on:
      - jenkins

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    expose:
      - 8080
      - 50000
    networks:
      - jenkins
    environment:
      - TZ=Europe/Madrid
    volumes:
      - jenkins-data:/var/jenkins_home
    healthcheck:
      test: curl -o /dev/null -s -w "%{http_code}\n" http://jenkins:8080
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s

  java-runner:
    build:
      context: .
      dockerfile: Dockerfile.java-runner
      args:
        - INBOUND_AGENT_VERSION=${INBOUND_AGENT_VERSION}
    networks:
      - jenkins
    environment:
      - TZ=Europe/Madrid
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${JAVA_RUNNER_SECRET}
      - JENKINS_AGENT_NAME=java-runner
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - java-runner-data:/home/jenkins/agent
    depends_on:
      jenkins:
        condition: service_healthy

  php-runner:
    build:
      context: .
      dockerfile: Dockerfile.php-runner
      args:
        - INBOUND_AGENT_VERSION=${INBOUND_AGENT_VERSION}
        - PHP_VERSION=${PHP_VERSION}
    networks:
      - jenkins
    environment:
      - TZ=Europe/Madrid
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${PHP_RUNNER_SECRET}
      - JENKINS_AGENT_NAME=php-runner
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - DOCKER_HOST=ssh://${JENKINS_DOCKER_USER}@${JENKINS_DOCKER_HOST}:${JENKINS_DOCKER_PORT}
    volumes:
      - php-runner-data:/home/jenkins/agent
    depends_on:
      jenkins:
        condition: service_healthy

networks:
  jenkins:

volumes:
  https-portal_certs:
  jenkins-data:
  java-runner-data:
  php-runner-data:
