services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-3}
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.rule=Host(`${FQDN_TRAEFIK:-traefik.test}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.service=api@internal"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-dashboard.tls=true"
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    depends_on:
      - jenkins

  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    expose:
      - 8080
      - 50000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-jenkins.rule=Host(`${FQDN_JENKINS:-jenkins.test}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-jenkins.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-jenkins.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-jenkins.loadbalancer.server.port=8080"
    networks:
      - jenkins
    environment:
      - TZ=Europe/Madrid
    volumes:
      - jenkins-data:/var/jenkins_home
    healthcheck:
      test: curl -o /dev/null -s -w "%{http_code}\n" http://jenkins:8080
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s

  java-runner:
    build:
      context: .
      dockerfile: docker/java-runner/Dockerfile
      args:
        - INBOUND_AGENT_VERSION=${INBOUND_AGENT_VERSION}
    networks:
      - jenkins
    environment:
      - TZ=Europe/Madrid
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${JAVA_RUNNER_SECRET}
      - JENKINS_AGENT_NAME=java-runner
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - java-runner-data:/home/jenkins
    depends_on:
      jenkins:
        condition: service_healthy

  php-runner:
    build:
      context: .
      dockerfile: docker/php-runner/Dockerfile
      args:
        - INBOUND_AGENT_VERSION=${INBOUND_AGENT_VERSION}
        - PHP_VERSION=${PHP_VERSION}
    networks:
      - jenkins
    environment:
      - TZ=Europe/Madrid
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${PHP_RUNNER_SECRET}
      - JENKINS_AGENT_NAME=php-runner
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - DOCKER_HOST=ssh://${JENKINS_DOCKER_USER}@${JENKINS_DOCKER_HOST}:${JENKINS_DOCKER_PORT}
    volumes:
      - php-runner-data:/home/jenkins
    depends_on:
      jenkins:
        condition: service_healthy

networks:
  jenkins:

volumes:
  https-portal_certs:
  jenkins-data:
  java-runner-data:
  php-runner-data:
